### ISSUE TITLE
Schema

### ISSUE THREAD

**Issue by PLUCS2** [andrewkihs/soundboard#2]
- [x] What is the difference between Username and Displayname on the Users table?
- [x] Songs can be on multiple playlists so the Songs table should not hold a Playlist_id 
- [x] The playlists table should have a joins table with the songs table so that songs can be associated with playlists 
- [x] You may want your songs to be associated with genre's or tags (create a genres or a tags table to accomplish this) 

Let me know if you have any questions and nice work!

**Comment by andrewkihs** [comment]
> * [ ]  What is the difference between Username and Displayname on the Users table?

This is similar to how Twitter users can have a handle (unique) and a display name (not unique, special characters, etc)

I implemented the other notes. I made a tags table and tags join table. Not sure if that is correct. I was thinking they behave in similar ways?
