### ISSUE TITLE
Sample State & Routes

### ISSUE THREAD

**Issue by vawhitehouse** [andrewkihs/soundboard#3]
## Sample State
- [x] You shouldn't need to keep an array of tags for songs. You should use your tagJoins to select the specific tags for each song.
- [x] You seem to have a mix of using `ID` and `Id` in some of you key names. These should all be following standard camelCase of only the first letter of a second word being capitalized -> `followerId` rather than `followerID`

## Backend Routes
These look really well thought out, nice job! Really just a few small typos:
- [x] Typo in your playlist GET route - you have a `.` instead of a `/`
- [x] Note in follow routes says comment instead of follow

Will you need a get route for tags?

## Frontend Routes
- [x] You won't be including anything non-functional in your clone - so things like  'Legal', 'Download' and maybe 'Who to follow' won't be necessary
- [x] Missing a backtick on `Search bar`
- You only need to list out the components that will be rendered on any given route - you seem to have a bit more of detailed breakdown (which is great to be thinking about!). For example, in the AudioPlayhead component, is skip/shuffle/forward/repeat a component or just part of whathe AudioPlayhead comonent will contain?

**Comment by andrewkihs** [comment]
>  You shouldn't need to keep an array of tags for songs. You should use your tagJoins to select the specific tags for each song.

Added a joinsTable slice of state. Might need a bit more direction on this but this can definitely wait until later in the week when I am able to schedule a meeting.
